### ISSUE TITLE
[Web] UI Wireframe

### ISSUE THREAD

**Issue by StephenODea54** [wetherc/dstk#37]
Wanted to discuss overall wireframe before fleshing out anything more complicated (figma, actual coding, etc) for #27 #28 and #29

I think the UI post-login lends itself to a sidebar + navbar + content type of layout (basically dashboard style application). Something along the lines of:

![image](https://github.com/wetherc/dstk/assets/77359138/cfef7c3b-c5db-4059-a981-13985c440d44)

**Comment by wetherc** [comment]
I'm totally down with the layout. I think the only couple questions I'd have are:

  - Can we move storage providers out of the main sidebar? I think we'd probably want to gatekeep that a little bit behind some sort of "team admin" permission and generally huck it into project settings. The storage providers will be seldom-changing, and shouldn't be something most users are able to access and muck around with.
  - Thoughts on reordering so that it's Models first, then Deployments second? Just order-of-operations-wise, a model has to exist before a deployment can so might as well reflect that in the sidebar hierarchy

**Comment by StephenODea54** [comment]
@wetherc fasho on everything you said. I'll get to it this afternoon.
